.\" Todos os Direitos Reservados. Este documento está em DOMINIO PÚBLICO.
.\" Kallisti.
.TH DDATE 1 "Burocracia 3161" "ddate" "Emperor Norton User Command"
.SH NAME
ddate \- Converte datas Gregorianas para as datas Discordianas
.SH SINOPSE
.B ddate
.RI [ \fB+\fPformato]
.RI [ data ]
.SH DESCRIÇÃO
.B ddate
mostra a data no formato Discordiano.
.PP
Se chamado sem nenhum argumento,
.B ddate
vai mostrar a data atual do sistema convertido para a data Discordiana e mostra-lá no modo padrão. De outro modo, uma data Gregoriana pode ser especificada na linha de comando no formato numérico de dia, mês e ano (ex. 25 12 2021). 
.PP
Para converter datas AC, colocar o ano como negativo (ex. 25 12 -100)
.PP
Se o formato de string for especificado, a data Discordiana irá ser mostrada no formato específico da string. Os campos são que podem ser utilizados são:
.IP %A
Nome inteiro do dia da semana (i.e., Docemanhã)
.IP %a
Nome abreviado do dia da semana (i.e., DM)
.IP %B
Nome da estações (i.e., Burocracia)
.IP %b
Nome abreviado da estação (i.e., Brc)
.IP %d
Número cardinal do dia da estação (i.e., 23)
.IP %e
Número ordinário do dia da estação (i.e., 23º)
.IP %H
Nome do feriado atual, se ouver algum
.IP %N
Código mágico para previnir que o resto do formato impresso a menos que hoje seja feriado
.IP %n
Nova Linha
.IP %t
Tab
.IP %X
Número de dias restantes até o dia X. (Não é valido se a opção do SubGenius não está compilada.)
.IP %Y
O ano da Nossa Senhora Da Discórdia (i.e., 3182)
.IP %{
.IP %}
Usado para encapsular parte de uma string que será substituida pelas palavras "Dia do Sto. Tiby" se for o dia do Sto. Tiby.
.IP %\.
Tente a sorte.
.bp
.SH EXEMPLOS
.nf
% ddate
.br
Docemanhã, 42 de Burocracia, 3161 YOLD
.PP
% ddate +'Hoje é %{%A, %e de %B%}, %Y. %N%nCelebramos %H'
.br
Hoje é  Docemanhã, 42º de Burocracia, 3161.
.PP
% ddate +"É  %{%A, %e de %B%}, %Y. %N%nCelebramos %H" 26 9 1995
.br
É Espinho-Espinho, 50º de Burocracia, 3161.
.br
Celebramos Bureflux
.PP
% ddate +"Hoje é  %{%A, %e de %B%}, %Y. %N%nCelebramos %H" 29 2 1996
.br
Hoje é dia do Sto. Tiby, 3162
.br

.SH BUGS

.B ddate(1)
Vai produzir um comportamento indefinido se for pedido para mostrar a data do Sto. Tiby se o formato da string não contiver os limitadores do Sto. Tiby %{ e %}.

.SH NOTA

Depois que o 'Dia-X' passou nem nenhum incidente, a Igreja do Subgênio declarou que tinha virado o ano de cabeça para baixo - então do Dia-X será em 8661 D.C. ao invés de 1998 A.C. Assim, o verdadeiro Dia-X será em 40 de Cfs, 9827.

.SH AUTOR
.nh
Programado originalmente por Druel, o Caotico, vulgo Jeremy Johnson (mpython@gnu.ai.mit.edu)
.br
Principal reescritor Lee H:. O:. Smith, KYTP, vulgo Andrew Bulhak (acb@dev.null.org)
.br
A.E.C (Antes da Era Comum), consertado pelo Chaplain Nyan, o Mais Sábio, vulgo Dan Dart (ntw@dandart.co.uk)
.br
Traduzido por Anderson Silvestre, vulgo Andy.
.br
Cinco toneladas de Linho.

.SH POLITICA DE DISTRIBUIÇÃO

Dominio Público. Todos os direitos reservados.

.SH VEJA TAMBÉM

date(1),
.br
http://www.subgenius.com/
.br
Malaclypse, O Mais Jovem ,
.I "Principia Discordia, Ou Como Eu Encontrei A Deusa E O Que Eu Fiz Com Ela Quando Eu A Encontrei"

.SH DISPONIBILIDADE
O ddate traduzido está disponível em https://github.com/bo0ts/ddate.

.SH DISPONIBILIDADE PROGRAMA ORIGINAL 
O comando ddate está disponível em https://github.com/bo0ts/ddate.
